### ISSUE TITLE
[BUG] Installation problem

### ISSUE THREAD

**Issue by debpal** [watem-sedem/watem-sedem#161]
**Describe the bug**
I cannot install through conda channel

**Screenshots**
I am getting lot of error in the Anaconda prompt. At the end, I am getting

**CondaSSLError: Encountered an SSL error. Most likely a certificate verification issue.

Exception: HTTPSConnectionPool(host='conda.static.fluves.net', port=443): Max retries exceeded with url: /win-64/current_repodata.json (Caused by SSLError(CertificateError("hostname 'conda.static.fluves.net' doesn't match either of '*.fluves.net', 'fluves.net'")))**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - CN-WS Version [conda channel]

**Comment by manmanju** [comment]
Hello, I faced the same error, did you solved it?

**Comment by johanvdw** [comment]
That will indeed not work. Where did you find these instructions? 
Anyway, you can download the binary from https://github.com/watem-sedem/watem-sedem/releases/tag/5.0.0
Looks like the binary from 5.0.1 is missing. I'll add it as well.
