### ISSUE TITLE
[DOCUMENTATION] Order of variables

### ISSUE THREAD

**Issue by SethCallewaert** [watem-sedem/watem-sedem#79]
Documentation references: https://github.com/cn-ws/cn-ws/blame/master/docs/input.rst#L406

**B. I have a question considering this section:**

Is there an order to the displayed variables? It seems to me that they are randomly ordered and loosely grouped, could be nice to see them ordered alphabetically or in another clear way (with clear grouping for example)?

Same counts for the files (would be interesting to indicate for which part of the model it is used)

**Comment by daarende** [comment]
I propose following order:

User Choices
* Only Routing
* Only WS
* L model
* S model
* TC Model
* Calculate tillage erosion
* Include sewers
* Include bufers
* Include dtiches
* Include dams
* Include tillage direction
* River Routing
* Force Routing

Files
* DTM filename
* K factor filename
* C factor map filename
* P factor map filename
* CN map filename
* ktc map filename
* ktil map filename
* Rainfall filename
* Parcel filename
* Sewer map filename
* Outlet map filename
* Buffer map filename
* Routing maps
* Ditch map filename
* Dam map filename
* river routing filename
* adjectant segments
* upstream segments
* River segment filename
* Tillage direction filename
* Oriented roughness filename

Variables
* R-factor
* ktc low
* ktc high
* ktc limit 
* ktl default
* ktil threshold
* Parcel connectivity cropland
* Parcel connectivity grassstrips
* Parcel connectivity forest
* Parcel trapping efficiency cropland
* Parcel trapping efficiency pasture
* Parcel trapping efficiency forest
* Number of buffers
* Number of forced routing
* LS correction
* bulk density
* Clay content parent material
* Sewer exit
* max kernel
* max kernel river
* 5-day antecedent rainfall
* stream velocity
* alpha
* beta
* Desired timestep for model
* Final timestep output
* Endtime model

I'll change the order when all other issues on the documentation are fixed to make it easier to fix these issues.

**Comment by daarende** [comment]
I'm closing this issue as we refactored the variables and user choices in https://github.com/cn-ws/watem-sedem/pull/145
